## Observations and Insights

In [3]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as st
import numpy as np
import os
import csv

# Study data files
mouse_metadata_path = "data/Mouse_metadata.csv"
study_results_path = "data/Study_results.csv"

# Read the mouse data and the study results
mouse_metadata = pd.read_csv(mouse_metadata_path)
study_results = pd.read_csv(study_results_path)

# Display the data table for preview

In [4]:
#preview data before merge
mouse_metadata.describe()

       Age_months  Weight (g)
count  249.000000  249.000000
mean    12.730924   26.116466
std      7.228687    3.697003
min      1.000000   15.000000
25%      6.000000   25.000000
50%     13.000000   27.000000
75%     19.000000   29.000000
max     24.000000   30.000000

In [5]:
#preview data before merge
study_results.describe()

         Timepoint  Tumor Volume (mm3)  Metastatic Sites
count  1893.000000         1893.000000       1893.000000
mean     19.572108           50.448381          1.021659
std      14.079460            8.894722          1.137974
min       0.000000           22.050126          0.000000
25%       5.000000           45.000000          0.000000
50%      20.000000           48.951474          1.000000
75%      30.000000           56.292200          2.000000
max      45.000000           78.567014          4.000000

In [6]:
#additional preview before merge
study_results.count()

Mouse ID              1893
Timepoint             1893
Tumor Volume (mm3)    1893
Metastatic Sites      1893
dtype: int64

In [7]:
#additional preview before merge
mouse_metadata.count()

Mouse ID        249
Drug Regimen    249
Sex             249
Age_months      249
Weight (g)      249
dtype: int64

In [8]:
# Combine the data into a single dataset
mouse_study_results = pd.merge(mouse_metadata,study_results,on='Mouse ID')

In [9]:
# Checking the number of mice.
mouse_study_results['Mouse ID'].value_counts()

g989    13
a275    10
j119    10
r944    10
b128    10
        ..
x226     1
u153     1
f932     1
b447     1
l872     1
Name: Mouse ID, Length: 249, dtype: int64

In [10]:
#sort values by Mouse ID
mouse_study_results.sort_values(by=['Mouse ID'])

,Mouse ID,Drug Regimen,Sex,Age_months,Weight (g),Timepoint,Tumor Volume (mm3),Metastatic Sites
460,a203,Infubinol,Female,20,23,30,59.523197,1
461,a203,Infubinol,Female,20,23,35,61.931650,2
459,a203,Infubinol,Female,20,23,25,56.793208,1
458,a203,Infubinol,Female,20,23,20,55.173336,1
457,a203,Infubinol,Female,20,23,15,52.777870,1
...,...,...,...,...,...,...,...,...
1887,z969,Naftisol,Male,9,30,20,57.898778,2
1888,z969,Naftisol,Male,9,30,25,63.145652,2
1889,z969,Naftisol,Male,9,30,30,65.841013,3
1890,z969,Naftisol,Male,9,30,35,69.176246,4
1892,z969,Naftisol,Male,9,30,45,73.867845,4

In [11]:
# Getting the duplicate mice by ID number that shows up for Mouse ID and Timepoint. 

mouse_study_duplicates = mouse_study_results.duplicated(keep=False)
print(mouse_study_duplicates)

0       False
1       False
2       False
3       False
4       False
        ...
1888    False
1889    False
1890    False
1891    False
1892    False
Length: 1893, dtype: bool

In [12]:
duplicate_values_table = mouse_study_results[mouse_study_duplicates]
duplicate_values_table.head()

,Mouse ID,Drug Regimen,Sex,Age_months,Weight (g),Timepoint,Tumor Volume (mm3),Metastatic Sites
908,g989,Propriva,Female,21,26,0,45.0,0
909,g989,Propriva,Female,21,26,0,45.0,0

In [13]:
#store ID for duplicated mouse
duplicated_mouse = 'g989'

In [14]:
# Optional: Get all the data for the duplicate mouse ID.
#view filtered dataframe on duplicate mouse
mouse_study_results[mouse_study_results['Mouse ID'] == duplicated_mouse]

,Mouse ID,Drug Regimen,Sex,Age_months,Weight (g),Timepoint,Tumor Volume (mm3),Metastatic Sites
908,g989,Propriva,Female,21,26,0,45.000000,0
909,g989,Propriva,Female,21,26,0,45.000000,0
910,g989,Propriva,Female,21,26,5,48.786801,0
911,g989,Propriva,Female,21,26,5,47.570392,0
912,g989,Propriva,Female,21,26,10,51.745156,0
913,g989,Propriva,Female,21,26,10,49.880528,0
914,g989,Propriva,Female,21,26,15,51.325852,1
915,g989,Propriva,Female,21,26,15,53.442020,0
916,g989,Propriva,Female,21,26,20,55.326122,1
917,g989,Propriva,Female,21,26,20,54.657650,1
918,g989,Propriva,Female,21,26,25,56.045564,1
919,g989,Propriva,Female,21,26,30,59.082294,1
920,g989,Propriva,Female,21,26,35,62.570880,2

In [15]:
# Create a clean DataFrame by dropping the duplicate mouse by its ID.
mouse_study = mouse_study_results[mouse_study_results['Mouse ID'] != duplicated_mouse]
mouse_study.head()

,Mouse ID,Drug Regimen,Sex,Age_months,Weight (g),Timepoint,Tumor Volume (mm3),Metastatic Sites
0,k403,Ramicane,Male,21,16,0,45.000000,0
1,k403,Ramicane,Male,21,16,5,38.825898,0
2,k403,Ramicane,Male,21,16,10,35.014271,1
3,k403,Ramicane,Male,21,16,15,34.223992,1
4,k403,Ramicane,Male,21,16,20,32.997729,1

In [16]:
#checking the number of mice in the clean DataFrame.
mouse_study['Mouse ID'].value_counts()

f345    10
x581    10
z969    10
c402    10
k382    10
        ..
x226     1
u153     1
f932     1
b447     1
l872     1
Name: Mouse ID, Length: 248, dtype: int64

## Summary Statistics

In [19]:
# Generate a summary statistics table of mean, median, variance, standard deviation, and SEM of the tumor volume for each regimen

# Use groupby and summary statistical methods to calculate the following properties of each drug regimen: 
# mean, median, variance, standard deviation, and SEM of the tumor volume. 
# Assemble the resulting series into a single summary dataframe.
mouse_study_drug_group = mouse_study.groupby("Drug Regimen").describe()
mouse_study_drug_group

             Age_months                                                     \
                  count       mean       std  min    25%   50%   75%   max
Drug Regimen
Capomulin         230.0  13.456522  7.721423  1.0   7.00  16.5  20.0  24.0
Ceftamin          178.0  13.247191  8.071406  2.0   6.00  12.0  20.0  24.0
Infubinol         178.0  16.230337  7.510278  1.0   8.00  20.0  23.0  24.0
Ketapril          188.0  15.659574  6.019670  1.0  11.75  18.0  19.0  24.0
Naftisol          186.0  12.000000  6.715855  2.0   8.00   9.0  19.0  23.0
Placebo           181.0  10.734807  6.354907  1.0   5.00  10.0  17.0  21.0
Propriva          148.0  10.006757  6.946341  1.0   5.00   7.5  16.0  24.0
Ramicane          228.0  10.684211  5.946629  1.0   7.00   9.0  18.0  23.0
Stelasyn          181.0  12.784530  7.939562  1.0   4.00  14.0  21.0  23.0
Zoniferol         182.0  12.598901  5.786114  2.0   8.00  12.5  16.0  24.0

             Weight (g)             ... Tumor Volume (mm3)             \
                  count       mean  ...                75%        max
Drug Regimen                        ...
Capomulin         230.0  19.965217  ...          45.000000  48.158209
Ceftamin          178.0  27.398876  ...          56.801438  68.923185
Infubinol         178.0  27.196629  ...          57.314444  72.226731
Ketapril          188.0  27.861702  ...          60.870951  78.567014
Naftisol          186.0  27.166667  ...          59.963034  76.668817
Placebo           181.0  27.928177  ...          59.916934  73.212939
Propriva          148.0  27.135135  ...          56.491585  72.455421
Ramicane          228.0  19.679825  ...          45.000000  47.622816
Stelasyn          181.0  27.856354  ...          58.719297  75.123690
Zoniferol         182.0  27.692308  ...          57.954259  73.324432

             Metastatic Sites
                        count      mean       std  min  25%  50%  75%  max
Drug Regimen
Capomulin               230.0  0.713043  0.848993  0.0  0.0  0.0  1.0  3.0
Ceftamin                178.0  1.179775  1.184283  0.0  0.0  1.0  2.0  4.0
Infubinol               178.0  0.960674  1.027104  0.0  0.0  1.0  2.0  4.0
Ketapril                188.0  1.297872  1.393873  0.0  0.0  1.0  2.0  4.0
Naftisol                186.0  1.182796  1.216519  0.0  0.0  1.0  2.0  4.0
Placebo                 181.0  1.441989  1.338824  0.0  0.0  1.0  2.0  4.0
Propriva                148.0  1.013514  1.106484  0.0  0.0  1.0  1.0  4.0
Ramicane                228.0  0.548246  0.691259  0.0  0.0  0.0  1.0  3.0
Stelasyn                181.0  0.872928  0.972046  0.0  0.0  1.0  1.0  4.0
Zoniferol               182.0  1.230769  1.248884  0.0  0.0  1.0  2.0  4.0

[10 rows x 40 columns]

In [20]:
#calculate variance
mouse_study_drug_group_var = mouse_study.groupby("Drug Regimen").var()
mouse_study_drug_group_var.head()

,Age_months,Weight (g),Timepoint,Tumor Volume (mm3),Metastatic Sites
Drug Regimen,,,,,
Capomulin,59.620372,7.466034,206.928043,24.947764,0.720790
Ceftamin,65.147591,2.501016,204.031772,39.290177,1.402527
Infubinol,56.404272,4.769028,181.534470,43.128684,1.054942
Ketapril,36.236432,3.392536,196.839089,68.553577,1.942883
Naftisol,45.102703,2.247748,201.208951,66.173479,1.479919

In [22]:
mouse_study_group_sem = mouse_study.groupby("Drug Regimen").sem()
mouse_study_group_sem.head()

,Age_months,Metastatic Sites,Mouse ID,Sex,Timepoint,Tumor Volume (mm3),Weight (g)
Drug Regimen,,,,,,,
Capomulin,0.509136,0.055981,NaN,NaN,0.948518,0.329346,0.180169
Ceftamin,0.604977,0.088766,NaN,NaN,1.070629,0.469821,0.118535
Infubinol,0.562919,0.076985,NaN,NaN,1.009879,0.492236,0.163684
Ketapril,0.439030,0.101659,NaN,NaN,1.023238,0.603860,0.134333
Naftisol,0.492430,0.089200,NaN,NaN,1.040081,0.596466,0.109930

In [24]:
tumor_vol_results = mouse_study_drug_group.join(mouse_study_drug_group_var,on="Drug Regimen")
tumor_vol_results.head()

C:\Users\eddie\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:618: UserWarning: merging between different levels can give an unintended result (2 levels on the left, 1 on the right)
  warnings.warn(msg, UserWarning)

,"(Age_months, count)","(Age_months, mean)","(Age_months, std)","(Age_months, min)","(Age_months, 25%)","(Age_months, 50%)","(Age_months, 75%)","(Age_months, max)","(Weight (g), count)","(Weight (g), mean)",...,"(Metastatic Sites, min)","(Metastatic Sites, 25%)","(Metastatic Sites, 50%)","(Metastatic Sites, 75%)","(Metastatic Sites, max)",Age_months,Weight (g),Timepoint,Tumor Volume (mm3),Metastatic Sites
Drug Regimen,,,,,,,,,,,,,,,,,,,,,
Capomulin,230.0,13.456522,7.721423,1.0,7.00,16.5,20.0,24.0,230.0,19.965217,...,0.0,0.0,0.0,1.0,3.0,59.620372,7.466034,206.928043,24.947764,0.720790
Ceftamin,178.0,13.247191,8.071406,2.0,6.00,12.0,20.0,24.0,178.0,27.398876,...,0.0,0.0,1.0,2.0,4.0,65.147591,2.501016,204.031772,39.290177,1.402527
Infubinol,178.0,16.230337,7.510278,1.0,8.00,20.0,23.0,24.0,178.0,27.196629,...,0.0,0.0,1.0,2.0,4.0,56.404272,4.769028,181.534470,43.128684,1.054942
Ketapril,188.0,15.659574,6.019670,1.0,11.75,18.0,19.0,24.0,188.0,27.861702,...,0.0,0.0,1.0,2.0,4.0,36.236432,3.392536,196.839089,68.553577,1.942883
Naftisol,186.0,12.000000,6.715855,2.0,8.00,9.0,19.0,23.0,186.0,27.166667,...,0.0,0.0,1.0,2.0,4.0,45.102703,2.247748,201.208951,66.173479,1.479919

In [25]:
tumor_vol_results_final = pd.merge(tumor_vol_results,mouse_study_group_sem,on="Drug Regimen",suffixes=(' var', ' SEM'))
tumor_vol_results_final.head()

,"(Age_months, count)","(Age_months, mean)","(Age_months, std)","(Age_months, min)","(Age_months, 25%)","(Age_months, 50%)","(Age_months, 75%)","(Age_months, max)","(Weight (g), count)","(Weight (g), mean)",...,Timepoint var,Tumor Volume (mm3) var,Metastatic Sites var,Age_months SEM,Metastatic Sites SEM,Mouse ID,Sex,Timepoint SEM,Tumor Volume (mm3) SEM,Weight (g) SEM
Drug Regimen,,,,,,,,,,,,,,,,,,,,,
Capomulin,230.0,13.456522,7.721423,1.0,7.00,16.5,20.0,24.0,230.0,19.965217,...,206.928043,24.947764,0.720790,0.509136,0.055981,NaN,NaN,0.948518,0.329346,0.180169
Ceftamin,178.0,13.247191,8.071406,2.0,6.00,12.0,20.0,24.0,178.0,27.398876,...,204.031772,39.290177,1.402527,0.604977,0.088766,NaN,NaN,1.070629,0.469821,0.118535
Infubinol,178.0,16.230337,7.510278,1.0,8.00,20.0,23.0,24.0,178.0,27.196629,...,181.534470,43.128684,1.054942,0.562919,0.076985,NaN,NaN,1.009879,0.492236,0.163684
Ketapril,188.0,15.659574,6.019670,1.0,11.75,18.0,19.0,24.0,188.0,27.861702,...,196.839089,68.553577,1.942883,0.439030,0.101659,NaN,NaN,1.023238,0.603860,0.134333
Naftisol,186.0,12.000000,6.715855,2.0,8.00,9.0,19.0,23.0,186.0,27.166667,...,201.208951,66.173479,1.479919,0.492430,0.089200,NaN,NaN,1.040081,0.596466,0.109930

In [26]:
#write summary stats to file
output_path = os.path.join("data","drug_summary_stats_total")
tumor_vol_results_final.to_csv(output_path, index=True)

In [28]:
#read in csv for cleaning

mouse_metadata_path = os.path.join("data","drug_summary_stats_total")

# Read the mouse data and the study results
mouse_tumorvol_stats = pd.read_csv(mouse_metadata_path,index_col=0)

mouse_tumorvol_stats

,"('Age_months', 'count')","('Age_months', 'mean')","('Age_months', 'std')","('Age_months', 'min')","('Age_months', '25%')","('Age_months', '50%')","('Age_months', '75%')","('Age_months', 'max')","('Weight (g)', 'count')","('Weight (g)', 'mean')",...,Timepoint var,Tumor Volume (mm3) var,Metastatic Sites var,Age_months SEM,Metastatic Sites SEM,Mouse ID,Sex,Timepoint SEM,Tumor Volume (mm3) SEM,Weight (g) SEM
Drug Regimen,,,,,,,,,,,,,,,,,,,,,
Capomulin,230.0,13.456522,7.721423,1.0,7.00,16.5,20.0,24.0,230.0,19.965217,...,206.928043,24.947764,0.720790,0.509136,0.055981,NaN,NaN,0.948518,0.329346,0.180169
Ceftamin,178.0,13.247191,8.071406,2.0,6.00,12.0,20.0,24.0,178.0,27.398876,...,204.031772,39.290177,1.402527,0.604977,0.088766,NaN,NaN,1.070629,0.469821,0.118535
Infubinol,178.0,16.230337,7.510278,1.0,8.00,20.0,23.0,24.0,178.0,27.196629,...,181.534470,43.128684,1.054942,0.562919,0.076985,NaN,NaN,1.009879,0.492236,0.163684
Ketapril,188.0,15.659574,6.019670,1.0,11.75,18.0,19.0,24.0,188.0,27.861702,...,196.839089,68.553577,1.942883,0.439030,0.101659,NaN,NaN,1.023238,0.603860,0.134333
Naftisol,186.0,12.000000,6.715855,2.0,8.00,9.0,19.0,23.0,186.0,27.166667,...,201.208951,66.173479,1.479919,0.492430,0.089200,NaN,NaN,1.040081,0.596466,0.109930
Placebo,181.0,10.734807,6.354907,1.0,5.00,10.0,17.0,21.0,181.0,27.928177,...,192.954266,61.168083,1.792449,0.472356,0.099514,NaN,NaN,1.032495,0.581331,0.136615
Propriva,148.0,10.006757,6.946341,1.0,5.00,7.5,16.0,24.0,148.0,27.135135,...,187.050699,43.852013,1.224306,0.570986,0.090952,NaN,NaN,1.124214,0.544332,0.140799
Ramicane,228.0,10.684211,5.946629,1.0,7.00,9.0,18.0,23.0,228.0,19.679825,...,203.796178,23.486704,0.477838,0.393825,0.045780,NaN,NaN,0.945433,0.320955,0.214244
Stelasyn,181.0,12.784530,7.939562,1.0,4.00,14.0,21.0,23.0,181.0,27.856354,...,191.620626,59.450562,0.944874,0.590143,0.072252,NaN,NaN,1.028921,0.573111,0.122169
Zoniferol,182.0,12.598901,5.786114,2.0,8.00,12.5,16.0,24.0,182.0,27.692308,...,206.918979,48.533355,1.559711,0.428895,0.092573,NaN,NaN,1.066263,0.516398,0.105229

In [31]:
# Generate a summary statistics table of mean, median, variance, standard deviation, and SEM of the tumor volume for each regimen

# Using the aggregation method, produce the same summary statistics in a single line

mouse_tumorvol_stats.aggregate(['mean','std','min','max','var','sem'],axis="columns")

                mean        std  min         max          var        sem
Capomulin  41.130201  70.726039  0.0  230.000000  5002.172655  10.002172
Ceftamin   38.559771  56.983890  0.0  204.031772  3247.163702   8.058739
Infubinol  38.048021  55.624814  0.0  181.534470  3094.119917   7.866537
Ketapril   40.134273  59.160076  0.0  196.839089  3499.914591   8.366498
Naftisol   39.600475  59.010512  0.0  201.208951  3482.240517   8.345347
Placebo    38.498681  57.273898  0.0  192.954266  3280.299360   8.099752
Propriva   34.428463  48.755722  0.0  187.050699  2377.120385   6.895100
Ramicane   40.001577  70.094528  0.0  228.000000  4913.242896   9.912863
Stelasyn   39.190890  57.217465  0.0  191.620626  3273.838315   8.091772
Zoniferol  38.551667  58.178940  0.0  206.918979  3384.789105   8.227745

## Bar and Pie Charts

In [9]:
# Generate a bar plot showing the total number of measurements taken on each drug regimen using pandas.

In [10]:
# Generate a bar plot showing the total number of measurements taken on each drug regimen using pyplot.

In [11]:
# Generate a pie plot showing the distribution of female versus male mice using pandas

In [12]:
# Generate a pie plot showing the distribution of female versus male mice using pyplot

## Quartiles, Outliers and Boxplots

In [13]:
# Calculate the final tumor volume of each mouse across four of the treatment regimens:  
# Capomulin, Ramicane, Infubinol, and Ceftamin

# Start by getting the last (greatest) timepoint for each mouse


# Merge this group df with the original dataframe to get the tumor volume at the last timepoint

In [14]:
# Put treatments into a list for for loop (and later for plot labels)


# Create empty list to fill with tumor vol data (for plotting)


# Calculate the IQR and quantitatively determine if there are any potential outliers. 

    
    # Locate the rows which contain mice on each drug and get the tumor volumes
    
    
    # add subset 
    
    
    # Determine outliers using upper and lower bounds

In [15]:
# Generate a box plot of the final tumor volume of each mouse across four regimens of interest

## Line and Scatter Plots

In [16]:
# Generate a line plot of tumor volume vs. time point for a mouse treated with Capomulin

In [17]:
# Generate a scatter plot of average tumor volume vs. mouse weight for the Capomulin regimen

## Correlation and Regression

In [18]:
# Calculate the correlation coefficient and linear regression model 
# for mouse weight and average tumor volume for the Capomulin regimen